version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - backend_public:/usr/src/app/public
      - backend_private:/usr/src/app/private
    depends_on:
      - postgres
      - redis
    networks:
      - ticketz

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backend_public:/var/www/backend-public/
    depends_on:
      - backend
    networks:
      - ticketz

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ticketzuser}
      - POSTGRES_DB=${POSTGRES_DB:-ticketz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-senhaSeguraTicketz2025}
      - TZ=America/Sao_Paulo
    networks:
      - ticketz

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - ticketz

networks:
  ticketz:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  backend_public:
  backend_private:
